modLoader="javafml"
loaderVersion="[28,)"
#issueTrackerURL="https://github.com/mrbysco/MODNAME/issues"

[[mods]]
modId="sfl"
version="${file.jarVersion}"
displayName="Server Friendly Looting"
#displayURL="https://www.curseforge.com/minecraft/mc-mods/MODNAME"
authors="ShyNieke, Mrbysco"
description='''Adds more server friendly ways of getting loot'''

[[dependencies.sfl]]
modId="forge"
mandatory=true
versionRange="[28,)"
ordering="NONE"
side="BOTH"

[[dependencies.sfl]]
modId="minecraft"
mandatory=true
versionRange="[1.14.4]"
ordering="NONE"
side="BOTH"