modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/mrbysco/Server-Friendly-Looting/issues"
license="MIT"

[[mods]]
modId="sfl"
version="${file.jarVersion}"
displayName="Server Friendly Looting"
displayURL="https://www.curseforge.com/minecraft/mc-mods/Server-Friendly-Looting"
authors="ShyNieke, Mrbysco"
description='''Adds more server friendly ways of getting loot'''
[[dependencies.sfl]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.sfl]]
modId="forge"
mandatory=true
versionRange="[41.0.94,)"
ordering="NONE"
side="BOTH"